name: Test
on:
  workflow_dispatch:

jobs:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send to Telegram
        run: |
          curl -X POST \
               -F "text=🔔 Test<br>Test" \
               -F "parse_mode=HTML" \
               -F "disable_web_page_preview=true" \
               "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage?chat_id=${TELEGRAM_CHAT_ID_MAIN}"
        env:
          VERSION: ${{ github.ref_name }}
          SHA256: ${{ env.SHA256 }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID_MAIN: ${{ secrets.TELEGRAM_CHAT_ID_MAIN }
