name: Test
on:
  workflow_dispatch:

jobs:
  test-job:  # Добавлено имя job [[6]]
    runs-on: ubuntu-latest  # Указана среда выполнения
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Правильная вложенность [[6]]

      - name: Send to Telegram
        run: |
          curl -X POST \
            -d '{
              "chat_id": "'"${TELEGRAM_CHAT_ID_MAIN}"'",
              "text": "🔔 <b>Test</b>\n\n1test",
              "parse_mode": "HTML",
              "disable_web_page_preview": true
            }' \
            --url "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage?chat_id=${TELEGRAM_CHAT_ID_MAIN}"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID_MAIN: ${{ secrets.DIRECT_MESSAGES }}
