name: Update Lists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'
      
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        run: |
          sudo apt update
          sudo apt install curl
          mkdir -p module module/ipset module/dnscrypt module/list
          curl -s https://raw.githubusercontent.com/V3nilla/IPSets-For-Bypass-in-Russia/refs/heads/main/ipset-amazon.txt > /tmp/ipset1.txt || true
          curl -s https://raw.githubusercontent.com/V3nilla/IPSets-For-Bypass-in-Russia/refs/heads/main/ipset-cloudflare.txt > /tmp/ipset2.txt || true
          cat /tmp/ipset1.txt /tmp/ipset2.txt > ./module/ipset/ipset-all.txt || true
          curl -s https://raw.githubusercontent.com/bol-van/rulist/refs/heads/main/reestr_hostname.txt -o ./module/list/reestr_hostname.txt || true
          curl -s https://raw.githubusercontent.com/sevcator/dnscrypt-proxy-stuff/refs/heads/main/cloaking-rules.txt -o ./module/dnscrypt/cloaking-rules.txt || true

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
      - name: Push to Main branch
        run: |
          git add ./module/ipset/ipset-all.txt
          git add ./module/list/reestr_hostname.txt
          git add ./module/dnscrypt/cloaking-rules.txt
          git commit -m "Update at $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin HEAD:main --force || echo "No changes to commit"
